#!/bin/bash

# Manual HPC Connection and Setup Script
# Run this in your Mac terminal (not in Antigravity)

echo "🖥️  IU Big Red 200 HPC - Manual Connection Guide"
echo "================================================"
echo ""

# Connection info
HPC_USER="madbala"
HPC_HOST="bigred200.uits.iu.edu"
ALLOCATION="c01949"

echo "Step 1: Connect to HPC"
echo "----------------------"
echo "Run this command in your terminal:"
echo ""
echo "  ssh ${HPC_USER}@${HPC_HOST}"
echo ""
echo "Enter your password when prompted: albuquerque56242002"
echo ""
read -p "Press Enter after you've logged into HPC..."

echo ""
echo "Step 2: Set Up SSH Key (Optional - for passwordless access)"
echo "-----------------------------------------------------------"
echo "On HPC, run these commands:"
echo ""
echo "  mkdir -p ~/.ssh"
echo "  chmod 700 ~/.ssh"
echo "  vi ~/.ssh/authorized_keys"
echo ""
echo "Then copy your public key from Mac:"
echo ""
cat ~/.ssh/id_rsa.pub
echo ""
echo "Paste it into authorized_keys on HPC, save and exit (:wq)"
echo ""
echo "  chmod 600 ~/.ssh/authorized_keys"
echo ""
read -p "Press Enter when done..."

echo ""
echo "Step 3: Request GPU Allocation"
echo "-------------------------------"
echo "On HPC, run:"
echo ""
echo "  salloc -A ${ALLOCATION} -N 1 -n 1 -t 2:00:00 --gres=gpu:1 --partition=gpu"
echo ""
echo "Wait for allocation message showing your node (e.g., nid00123)"
echo ""
read -p "Press Enter after GPU is allocated..."

echo ""
echo "Step 4: SSH to Compute Node"
echo "----------------------------"
echo "On HPC, run:"
echo ""
echo "  ssh \$(scontrol show hostname \$SLURM_NODELIST)"
echo ""
echo "Or manually: ssh nid<your_node_number>"
echo ""
read -p "Press Enter after connecting to compute node..."

echo ""
echo "Step 5: Load Python Environment"
echo "--------------------------------"
echo "On compute node, run:"
echo ""
echo "  module load python/gpu/3.10.10"
echo "  python3 --version"
echo ""
read -p "Press Enter after Python is loaded..."

echo ""
echo "Step 6: Transfer Project Files"
echo "-------------------------------"
echo "OPEN A NEW TERMINAL WINDOW ON YOUR MAC and run:"
echo ""
echo "  cd /Users/madhavanbalaji/Documents/CV"
echo "  rsync -avz --exclude='*.pyc' --exclude='__pycache__' \\"
echo "        --exclude='outputs' --exclude='uploads' \\"
echo "        --exclude='.venv' --exclude='venv' --exclude='.git' \\"
echo "        project/ ${HPC_USER}@${HPC_HOST}:~/cv_project/"
echo ""
echo "Enter password when prompted."
echo ""
read -p "Press Enter after files are transferred..."

echo ""
echo "Step 7: Set Up Python Virtual Environment"
echo "------------------------------------------"
echo "Back on HPC compute node, run:"
echo ""
echo "  cd ~/cv_project/backend"
echo "  python3 -m venv ~/cv_env"
echo "  source ~/cv_env/bin/activate"
echo "  pip install --upgrade pip"
echo ""
read -p "Press Enter after virtual environment is ready..."

echo ""
echo "Step 8: Install Dependencies"
echo "-----------------------------"
echo "On HPC (with venv activated), run:"
echo ""
echo "  pip install -r requirements.txt"
echo ""
echo "This will take 5-10 minutes..."
echo ""
read -p "Press Enter after installation completes..."

echo ""
echo "Step 9: Download Pre-trained Models"
echo "------------------------------------"
echo "On HPC, run:"
echo ""
echo "  cd ~/cv_project/backend"
echo "  mkdir -p neural_style/models"
echo "  cd neural_style/models"
echo ""
echo "  wget https://download.pytorch.org/models/mosaic-9e94bfb3.pth -O mosaic.pth"
echo "  wget https://download.pytorch.org/models/candy-9e94bfb3.pth -O candy.pth"
echo "  wget https://download.pytorch.org/models/udnie-9e94bfb3.pth -O udnie.pth"
echo "  wget https://download.pytorch.org/models/rain-princess-9e94bfb3.pth -O rain_princess.pth"
echo ""
read -p "Press Enter after models are downloaded..."

echo ""
echo "Step 10: Test Backend"
echo "---------------------"
echo "On HPC, run:"
echo ""
echo "  cd ~/cv_project/backend"
echo "  python3 -c \"from gan_inference import apply_gan; print('GAN loaded')\""
echo "  python3 -c \"import torch; print('CUDA available:', torch.cuda.is_available())\""
echo ""
read -p "Press Enter after tests pass..."

echo ""
echo "Step 11: Start Backend Server"
echo "------------------------------"
echo "On HPC, run:"
echo ""
echo "  cd ~/cv_project/backend"
echo "  uvicorn main:app --host 0.0.0.0 --port 8000"
echo ""
echo "Keep this terminal open."
echo ""

echo ""
echo "Step 12: Set Up SSH Tunnel (for remote access)"
echo "-----------------------------------------------"
echo "OPEN ANOTHER NEW TERMINAL ON YOUR MAC and run:"
echo ""
echo "  ssh -L 8000:localhost:8000 ${HPC_USER}@${HPC_HOST}"
echo ""
echo "Then on that SSH session:"
echo "  ssh -L 8000:localhost:8000 nid<your_node_number>"
echo ""
echo "This creates a tunnel from your Mac to the HPC backend."
echo ""

echo ""
echo "✨ All Done!"
echo "============"
echo ""
echo "Now you can access your backend at:"
echo "  http://localhost:8000/docs  (from your Mac browser)"
echo ""
echo "And your frontend at:"
echo "  http://localhost:3000  (already running locally)"
echo ""
echo "The frontend will connect to the HPC backend via the SSH tunnel!"
echo ""
